services:
  - type: web
    name: campus-runner-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py "app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: sqlite:///campusrunner.db
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: CORS_ORIGINS
        value: https://campus-runner-gbmut5rt4-rachanab5s-projects.vercel.app
      # Set MAIL_USERNAME and MAIL_PASSWORD manually in Render dashboard

  - type: static
    name: campus-runner-frontend
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://campus-runner-2w67.onrender.com/api
