#!/usr/bin/env python3
"""
Seed script to populate the database with the real RV University canteen menu.
Run: python seed.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import app, db
from models import Food
import uuid

MENU_ITEMS = [
    # ── MEALS ─────────────────────────────────────────────────────────
    {"name": "North Mini Meals", "category": "Meals", "price": 70,
     "description": "A wholesome North Indian mini thali with dal, sabzi, roti and rice",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop"},
    {"name": "North Full Meals", "category": "Meals", "price": 120,
     "description": "Full North Indian thali with dal, 2 sabzis, roti, rice, salad and pickle",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=300&fit=crop"},
    {"name": "South Mini Meals", "category": "Meals", "price": 50,
     "description": "South Indian mini meals with rice, sambar, rasam and 2 curries",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1567337710282-00832b415979?w=400&h=300&fit=crop"},
    {"name": "South Full Meals", "category": "Meals", "price": 100,
     "description": "Full South Indian banana leaf style meals with rice, sambar, rasam and 3 curries",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400&h=300&fit=crop"},

    # ── NORTH INDIAN ──────────────────────────────────────────────────
    {"name": "Poori Chole", "category": "North Indian", "price": 60,
     "description": "Fluffy puris served with spicy chickpea curry",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop"},
    {"name": "Chole Batura", "category": "North Indian", "price": 90,
     "description": "Soft bhatura with spiced chole — a North Indian classic",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1626082927389-6cd097cee6a2?w=400&h=300&fit=crop"},
    {"name": "Dal Khichadi", "category": "North Indian", "price": 70,
     "description": "Comfort food — rice cooked with yellow dal, ghee and cumin",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=400&h=300&fit=crop"},

    # ── COMBOS ────────────────────────────────────────────────────────
    {"name": "Jeera Rice with Dal Tadka", "category": "Combos", "price": 70,
     "description": "Aromatic jeera rice paired with smoky dal tadka",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop"},
    {"name": "Rajma / Chole Rice", "category": "Combos", "price": 70,
     "description": "Steamed rice with rich rajma or chole curry",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1567337710282-00832b415979?w=400&h=300&fit=crop"},
    {"name": "Aloo Paratha with Chole", "category": "Combos", "price": 80,
     "description": "Stuffed potato paratha served with spicy chole",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop"},
    {"name": "Paneer Curry Combo", "category": "Combos", "price": 120,
     "description": "Soft paneer in rich tomato gravy with rice or roti",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&h=300&fit=crop"},
    {"name": "Veg Chinese Combo", "category": "Combos", "price": 120,
     "description": "Veg fried rice or veg noodles served with Manchurian",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&h=300&fit=crop"},
    {"name": "Non Veg Chinese Combo", "category": "Combos", "price": 150,
     "description": "Chicken fried rice or noodles with Manchurian",
     "is_veg": False, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop"},
    {"name": "Chicken Curry Combo", "category": "Combos", "price": 120,
     "description": "Tender chicken curry served with rice or 2 rotis",
     "is_veg": False, "prep_time": 20,
     "image_url": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&h=300&fit=crop"},
    {"name": "Egg Curry Combo", "category": "Combos", "price": 100,
     "description": "Boiled eggs in spicy onion-tomato gravy with rice or roti",
     "is_veg": False, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1647888162325-346cc541bcc9?w=400&h=300&fit=crop"},

    # ── BIRIYANIS ─────────────────────────────────────────────────────
    {"name": "Veg Hyderabadi Biryani", "category": "Biriyanis", "price": 100,
     "description": "Aromatic basmati rice layered with spiced vegetables and saffron",
     "is_veg": True, "prep_time": 25,
     "image_url": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop"},
    {"name": "Mushroom Donne Biryani", "category": "Biriyanis", "price": 120,
     "description": "Donne-style biryani with mushrooms served in a leaf bowl",
     "is_veg": True, "prep_time": 25,
     "image_url": "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400&h=300&fit=crop"},
    {"name": "Egg Hyderabadi Biryani", "category": "Biriyanis", "price": 110,
     "description": "Fragrant biryani with boiled eggs and dum-cooked spices",
     "is_veg": False, "prep_time": 25,
     "image_url": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop"},
    {"name": "Chicken Hyderabadi Biryani", "category": "Biriyanis", "price": 140,
     "description": "Classic dum biryani with tender chicken marinated in spices",
     "is_veg": False, "prep_time": 30,
     "image_url": "https://images.unsplash.com/photo-1714611626323-5ba6204453be?w=400&h=300&fit=crop"},
    {"name": "Chicken Donne Biryani", "category": "Biriyanis", "price": 140,
     "description": "Donne-style chicken biryani — Bangalore's favourite street style",
     "is_veg": False, "prep_time": 30,
     "image_url": "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop"},
    {"name": "Chicken Kabab Biryani", "category": "Biriyanis", "price": 150,
     "description": "Biryani with smoky chicken kabab pieces layered through",
     "is_veg": False, "prep_time": 30,
     "image_url": "https://images.unsplash.com/photo-1633945274417-da79a1f93df2?w=400&h=300&fit=crop"},

    # ── PARATHAS ──────────────────────────────────────────────────────
    {"name": "Aloo Paratha with Curd", "category": "Parathas", "price": 70,
     "description": "Crispy potato-stuffed wheat paratha served with fresh curd",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop"},
    {"name": "Aloo Cheese Paratha", "category": "Parathas", "price": 90,
     "description": "Potato and cheese stuffed paratha with curd on the side",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1604152135912-04a022e23696?w=400&h=300&fit=crop"},
    {"name": "Aloo Paneer Mix Paratha", "category": "Parathas", "price": 90,
     "description": "Mixed aloo and paneer stuffed paratha with curd",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&h=300&fit=crop"},
    {"name": "Paneer Paratha with Curd", "category": "Parathas", "price": 90,
     "description": "Cottage cheese stuffed paratha, golden toasted with curd",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop"},
    {"name": "Paneer Cheese Paratha", "category": "Parathas", "price": 110,
     "description": "Double indulgence — paneer and cheese stuffed paratha with curd",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop"},

    # ── PASTA ─────────────────────────────────────────────────────────
    {"name": "Pasta Creamy Alfredo", "category": "Pasta", "price": 70,
     "description": "Penne in rich white sauce with herbs and cream",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop"},
    {"name": "Alfredo with Cheese", "category": "Pasta", "price": 80,
     "description": "Creamy white sauce pasta loaded with extra cheese",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=400&h=300&fit=crop"},
    {"name": "Peri Peri Mac N Cheese", "category": "Pasta", "price": 90,
     "description": "Spicy peri peri flavoured macaroni and cheese",
     "is_veg": True, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=400&h=300&fit=crop"},

    # ── PIZZA & BREAD ─────────────────────────────────────────────────
    {"name": "Chessy Garlic Bread", "category": "Pizza & Bread", "price": 50,
     "description": "Toasted garlic bread loaded with melted cheese",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?w=400&h=300&fit=crop"},
    {"name": "Margherita Pizza", "category": "Pizza & Bread", "price": 100,
     "description": "Classic tomato sauce and mozzarella on a thin crust",
     "is_veg": True, "prep_time": 20,
     "image_url": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop"},
    {"name": "Tandoori Paneer Pizza", "category": "Pizza & Bread", "price": 120,
     "description": "Pizza with tandoori paneer, capsicum and onion topping",
     "is_veg": True, "prep_time": 20,
     "image_url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop"},
    {"name": "Tandoori Mushroom Pizza", "category": "Pizza & Bread", "price": 120,
     "description": "Mushroom and capsicum pizza with tandoori seasoning",
     "is_veg": True, "prep_time": 20,
     "image_url": "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop"},
    {"name": "Bread Paneer Pizza", "category": "Pizza & Bread", "price": 50,
     "description": "Paneer topping on toasted bread pizza base",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=400&h=300&fit=crop"},
    {"name": "Bread Mushroom Pizza", "category": "Pizza & Bread", "price": 50,
     "description": "Mushroom and cheese on a toasted bread pizza base",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=300&fit=crop"},

    # ── ROLLS ─────────────────────────────────────────────────────────
    {"name": "Veg Roll", "category": "Rolls", "price": 70,
     "description": "Spiced vegetables wrapped in a crispy paratha roll",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop"},
    {"name": "Paneer Roll", "category": "Rolls", "price": 90,
     "description": "Grilled paneer with onion and chutney in a paratha wrap",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop"},
    {"name": "Egg Roll", "category": "Rolls", "price": 70,
     "description": "Egg omelette with masala and onion in a paratha roll",
     "is_veg": False, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=400&h=300&fit=crop"},
    {"name": "Chicken Roll", "category": "Rolls", "price": 100,
     "description": "Juicy chicken tikka pieces wrapped in a soft paratha",
     "is_veg": False, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=400&h=300&fit=crop"},
    {"name": "Peri Peri Chicken Roll", "category": "Rolls", "price": 100,
     "description": "Spicy peri peri chicken with mayo in a paratha wrap",
     "is_veg": False, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop"},
    {"name": "BBQ Chicken Roll", "category": "Rolls", "price": 100,
     "description": "BBQ glazed chicken with crunchy slaw in a paratha",
     "is_veg": False, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=400&h=300&fit=crop"},

    # ── BURGERS ───────────────────────────────────────────────────────
    {"name": "Veg Burger", "category": "Burgers", "price": 60,
     "description": "Crispy veggie patty with fresh lettuce, tomatoes and special sauce",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1550547660-d9450f859349?w=400&h=300&fit=crop"},
    {"name": "Chicken Burger", "category": "Burgers", "price": 70,
     "description": "Juicy chicken patty with crisp lettuce and mayo",
     "is_veg": False, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop"},
    {"name": "Peri Peri Chicken Burger", "category": "Burgers", "price": 90,
     "description": "Spicy peri peri chicken fillet with coleslaw",
     "is_veg": False, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=400&h=300&fit=crop"},
    {"name": "BBQ Chicken Burger", "category": "Burgers", "price": 90,
     "description": "BBQ glazed chicken with pickles and smoky sauce",
     "is_veg": False, "prep_time": 15,
     "image_url": "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?w=400&h=300&fit=crop"},
    {"name": "Vada Pav", "category": "Burgers", "price": 30,
     "description": "Mumbai's street food classic — spiced potato vada in a soft pav",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=400&h=300&fit=crop"},
    {"name": "Bun Samosa", "category": "Burgers", "price": 40,
     "description": "Crispy samosa stuffed inside a pav with chutney",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1697155836252-d7f969108b5a?w=400&h=300&fit=crop"},

    # ── MAGGI ─────────────────────────────────────────────────────────
    {"name": "Maggi Masala", "category": "Maggi", "price": 35,
     "description": "Classic Maggi noodles cooked with masala",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&h=300&fit=crop"},
    {"name": "Peri Peri / Extra Masala Maggi", "category": "Maggi", "price": 45,
     "description": "Spiced-up Maggi with peri peri, extra masala, corn or cheese",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=400&h=300&fit=crop"},
    {"name": "Maggi Special", "category": "Maggi", "price": 50,
     "description": "Maggi with extra masala or peri peri and extra cheese",
     "is_veg": True, "prep_time": 10,
     "image_url": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=400&h=300&fit=crop"},

    # ── BEVERAGES: LASSI ──────────────────────────────────────────────
    {"name": "Buttermilk", "category": "Beverages", "price": 25,
     "description": "Chilled salted buttermilk with cumin and curry leaves",
     "is_veg": True, "prep_time": 2,
     "image_url": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop"},
    {"name": "Sweet Lassi", "category": "Beverages", "price": 50,
     "description": "Chilled sweet yoghurt drink",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=400&h=300&fit=crop"},
    {"name": "Strawberry Lassi", "category": "Beverages", "price": 65,
     "description": "Thick yoghurt lassi blended with fresh strawberry",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop"},
    {"name": "Chocolate Lassi", "category": "Beverages", "price": 65,
     "description": "Creamy lassi blended with chocolate syrup",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop"},
    {"name": "Mango Banana Rose Lassi", "category": "Beverages", "price": 65,
     "description": "Thick lassi blended with mango, banana and rose syrup",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop"},

    # ── BEVERAGES: FRESH JUICES ───────────────────────────────────────
    {"name": "Lemon Juice", "category": "Beverages", "price": 25,
     "description": "Fresh squeezed lemon juice with a pinch of salt and sugar",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop"},
    {"name": "Watermelon / Muskmelon Juice", "category": "Beverages", "price": 40,
     "description": "Chilled fresh watermelon or muskmelon juice",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop"},
    {"name": "Pineapple Juice", "category": "Beverages", "price": 40,
     "description": "Fresh pineapple juice — sweet and tangy",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1534353473418-4cfa0ac2f85b?w=400&h=300&fit=crop"},
    {"name": "Orange / Mosambi Juice", "category": "Beverages", "price": 40,
     "description": "Fresh squeezed orange or mosambi juice",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=300&fit=crop"},
    {"name": "Ganga Jamuna Juice", "category": "Beverages", "price": 40,
     "description": "Two layered juice — orange and lime blended together",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1546171753-97d7676e4602?w=400&h=300&fit=crop"},
    {"name": "Mix Fruit Juice", "category": "Beverages", "price": 50,
     "description": "Blend of seasonal fruits for a refreshing glass",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1546171753-97d7676e4602?w=400&h=300&fit=crop"},

    # ── BEVERAGES: SODA ───────────────────────────────────────────────
    {"name": "Fresh Lime Soda", "category": "Beverages", "price": 35,
     "description": "Zingy fresh lime soda — sweet or salted",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop"},
    {"name": "Masala Lemon Soda", "category": "Beverages", "price": 40,
     "description": "Spiced masala lemon soda with chaat masala",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop"},
    {"name": "Blue Lagoon Soda", "category": "Beverages", "price": 50,
     "description": "Cool blue lagoon soda with lemon",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&h=300&fit=crop"},
    {"name": "Mango Soda", "category": "Beverages", "price": 50,
     "description": "Chilled mango flavoured soda",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop"},
    {"name": "Kala Khatta Soda", "category": "Beverages", "price": 50,
     "description": "Tangy kala khatta syrup with chilled soda",
     "is_veg": True, "prep_time": 3,
     "image_url": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&h=300&fit=crop"},

    # ── BEVERAGES: MILK SHAKES ────────────────────────────────────────
    {"name": "Vanilla / Chocolate Shake", "category": "Beverages", "price": 50,
     "description": "Classic milk shake in vanilla or chocolate flavour",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop"},
    {"name": "Butterscotch / Black Currant Shake", "category": "Beverages", "price": 50,
     "description": "Butterscotch or black currant milk shake",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1615478503562-ec2d8aa0e24e?w=400&h=300&fit=crop"},
    {"name": "Mango Milk Shake", "category": "Beverages", "price": 50,
     "description": "Rich and creamy mango milk shake",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1697642452436-9c40773cbcbb?w=400&h=300&fit=crop"},
    {"name": "Cold Coffee with Ice Cream", "category": "Beverages", "price": 65,
     "description": "Chilled coffee blended with ice cream — rich and indulgent",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1530569673472-307dc017a82d?w=400&h=300&fit=crop"},
    {"name": "Oreo Shake", "category": "Beverages", "price": 65,
     "description": "Blended Oreo cookies with milk and ice cream",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1615478503562-ec2d8aa0e24e?w=400&h=300&fit=crop"},
    {"name": "Chocolate Brownie Shake", "category": "Beverages", "price": 65,
     "description": "Rich chocolate brownie blended into a creamy shake",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop"},
    {"name": "KitKat Shake", "category": "Beverages", "price": 65,
     "description": "KitKat blended into a creamy milk shake",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=400&h=300&fit=crop"},
    {"name": "Rose Milk Shake", "category": "Beverages", "price": 65,
     "description": "Chilled rose-flavoured milk shake",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop"},

    # ── BEVERAGES: TEA & COFFEE ───────────────────────────────────────
    {"name": "Regular Tea / Filter Coffee", "category": "Beverages", "price": 15,
     "description": "Freshly brewed cutting chai or South Indian filter coffee",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=400&h=300&fit=crop"},
    {"name": "Fresh Lime Tea", "category": "Beverages", "price": 15,
     "description": "Hot lime tea with ginger and honey",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop"},
    {"name": "Black Tea / Black Coffee", "category": "Beverages", "price": 15,
     "description": "Strong black tea or black coffee",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop"},
    {"name": "Ginger Tea / Ginger Coffee", "category": "Beverages", "price": 17,
     "description": "Warming ginger tea or ginger-spiced coffee",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=300&fit=crop"},
    {"name": "Café Mocha", "category": "Beverages", "price": 25,
     "description": "Espresso with steamed milk and chocolate sauce",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop"},
    {"name": "Hot Chocolate", "category": "Beverages", "price": 25,
     "description": "Rich and creamy hot chocolate",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?w=400&h=300&fit=crop"},

    # ── BEVERAGES: PACKAGED ───────────────────────────────────────────
    {"name": "Coke / Sprite / Fanta", "category": "Beverages", "price": 20,
     "description": "Chilled Coca-Cola, Sprite, Fanta, Thums Up or Limca",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=400&h=300&fit=crop"},
    {"name": "Campa Cola", "category": "Beverages", "price": 10,
     "description": "Campa Cola, Lemon, Orange or Energy — retro Indian drinks",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1585252168681-e6b15f87c2a5?w=400&h=300&fit=crop"},
    {"name": "Smoodh Drink", "category": "Beverages", "price": 20,
     "description": "Chocolate Milk, Toffee Caramel, Hazelnut or Coffee Frappe",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop"},
    {"name": "Paper Boat", "category": "Beverages", "price": 25,
     "description": "Alphonso Mango, Lychee, Apple, Aamras or Orange",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1464347744102-11db6282f854?w=400&h=300&fit=crop"},
    {"name": "Coconut Water", "category": "Beverages", "price": 60,
     "description": "Fresh chilled coconut water",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop"},

    # ── SNACKS / FRUIT ────────────────────────────────────────────────
    {"name": "Fresh Fruit Bowl", "category": "Snacks", "price": 50,
     "description": "Seasonal fresh cut fruits served chilled",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=300&fit=crop"},
    {"name": "Fruit Bowl with Ice Cream", "category": "Snacks", "price": 65,
     "description": "Fresh fruit bowl topped with a scoop of ice cream",
     "is_veg": True, "prep_time": 5,
     "image_url": "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=400&h=300&fit=crop"},

    # ── ICE CREAM ─────────────────────────────────────────────────────
    {"name": "Alphonso Mango Ice Cream", "category": "Ice Cream", "price": 25,
     "description": "Dairy Day — Real Alphonso mango ice cream",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400&h=300&fit=crop"},
    {"name": "Chocolate / Butterscotch Cone", "category": "Ice Cream", "price": 40,
     "description": "Dairy Day ice cream cone — chocolate or butterscotch",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=300&fit=crop"},
    {"name": "Triple Sundae Ice Cream", "category": "Ice Cream", "price": 60,
     "description": "Ideal — Triple sundae with three scoops and toppings",
     "is_veg": True, "prep_time": 2,
     "image_url": "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop"},
    {"name": "Kulfi Candy", "category": "Ice Cream", "price": 30,
     "description": "Ideal — Traditional Indian kulfi on a stick",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=400&h=300&fit=crop"},
    {"name": "Matka Kulfi", "category": "Ice Cream", "price": 50,
     "description": "Ideal — Traditional creamy kulfi served in a clay pot",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=400&h=300&fit=crop"},
    {"name": "Kaju Malai Ice Cream", "category": "Ice Cream", "price": 50,
     "description": "Ideal — Rich cashew and cream ice cream",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1488900128323-21503983a07e?w=400&h=300&fit=crop"},
    {"name": "Chikku Almond Ice Cream", "category": "Ice Cream", "price": 50,
     "description": "Ideal — Sapodilla (chikku) and almond ice cream",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&h=300&fit=crop"},
    {"name": "Cassata Ice Cream", "category": "Ice Cream", "price": 50,
     "description": "Ideal — Layered cassata with fruit and nut ice cream",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=400&h=300&fit=crop"},
    {"name": "Mini Sundae Chocolate", "category": "Ice Cream", "price": 20,
     "description": "Ideal — Mini chocolate sundae ice cream",
     "is_veg": True, "prep_time": 1,
     "image_url": "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400&h=300&fit=crop"},
]


def seed_menu():
    with app.app_context():
        existing = Food.query.count()
        if existing > 0:
            print(f"Database already has {existing} food items. Clearing and re-seeding...")
            Food.query.delete()
            db.session.commit()

        print(f"Seeding {len(MENU_ITEMS)} menu items...")
        for item_data in MENU_ITEMS:
            food = Food(
                id=str(uuid.uuid4()),
                name=item_data["name"],
                category=item_data["category"],
                price=item_data["price"],
                description=item_data["description"],
                is_veg=item_data.get("is_veg", True),
                prep_time=item_data.get("prep_time", 15),
                image_url=item_data.get("image_url", ""),
                available=True,
                rating=4.5,
                review_count=0,
            )
            db.session.add(food)

        db.session.commit()
        print(f"✅ Successfully seeded {len(MENU_ITEMS)} menu items!")

        # Print category summary
        from sqlalchemy import func
        categories = db.session.query(Food.category, func.count(Food.id)).group_by(Food.category).all()
        print("\nCategory summary:")
        for cat, count in sorted(categories):
            print(f"  {cat}: {count} items")


if __name__ == "__main__":
    seed_menu()